/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BountyEscrow {
  export type BountyStruct = {
    creator: AddressLike;
    amount: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    winner: AddressLike;
    metadataHash: BytesLike;
    createdAt: BigNumberish;
    submissionCount: BigNumberish;
  };

  export type BountyStructOutput = [
    creator: string,
    amount: bigint,
    deadline: bigint,
    status: bigint,
    winner: string,
    metadataHash: string,
    createdAt: bigint,
    submissionCount: bigint
  ] & {
    creator: string;
    amount: bigint;
    deadline: bigint;
    status: bigint;
    winner: string;
    metadataHash: string;
    createdAt: bigint;
    submissionCount: bigint;
  };

  export type SubmissionStruct = {
    submitter: AddressLike;
    contentHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type SubmissionStructOutput = [
    submitter: string,
    contentHash: string,
    timestamp: bigint
  ] & { submitter: string; contentHash: string; timestamp: bigint };
}

export interface BountyEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DIVISOR"
      | "PLATFORM_FEE_BPS"
      | "REFUND_GRACE_PERIOD"
      | "bounties"
      | "bountySubmissionCount"
      | "cancelBounty"
      | "claimRefund"
      | "createBounty"
      | "getBounty"
      | "getBountyCount"
      | "getSubmission"
      | "getSubmissionCount"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "selectWinner"
      | "submissions"
      | "submitWork"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateTreasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BountyCancelled"
      | "BountyCreated"
      | "OwnershipTransferred"
      | "Paused"
      | "RefundClaimed"
      | "SubmissionCreated"
      | "TreasuryUpdated"
      | "Unpaused"
      | "WinnerSelected"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REFUND_GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bounties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bountySubmissionCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createBounty",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBounty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBountyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmission",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubmissionCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "selectWinner",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REFUND_GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bounties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bountySubmissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBounty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBountyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubmissionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
}

export namespace BountyCancelledEvent {
  export type InputTuple = [bountyId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [bountyId: bigint, creator: string];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BountyCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish,
    deadline: BigNumberish,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    creator: string,
    amount: bigint,
    deadline: bigint,
    metadataHash: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    amount: bigint;
    deadline: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [bountyId: bigint, creator: string, amount: bigint];
  export interface OutputObject {
    bountyId: bigint;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionCreatedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    submissionId: BigNumberish,
    submitter: AddressLike,
    contentHash: BytesLike
  ];
  export type OutputTuple = [
    bountyId: bigint,
    submissionId: bigint,
    submitter: string,
    contentHash: string
  ];
  export interface OutputObject {
    bountyId: bigint;
    submissionId: bigint;
    submitter: string;
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerSelectedEvent {
  export type InputTuple = [
    bountyId: BigNumberish,
    submissionId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    bountyId: bigint,
    submissionId: bigint,
    winner: string,
    amount: bigint
  ];
  export interface OutputObject {
    bountyId: bigint;
    submissionId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BountyEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): BountyEscrow;
  waitForDeployment(): Promise<this>;

  interface: BountyEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DIVISOR: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  REFUND_GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  bounties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string, bigint, bigint] & {
        creator: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        winner: string;
        metadataHash: string;
        createdAt: bigint;
        submissionCount: bigint;
      }
    ],
    "view"
  >;

  bountySubmissionCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  cancelBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [bountyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createBounty: TypedContractMethod<
    [amount: BigNumberish, deadline: BigNumberish, metadataHash: BytesLike],
    [bigint],
    "payable"
  >;

  getBounty: TypedContractMethod<
    [bountyId: BigNumberish],
    [BountyEscrow.BountyStructOutput],
    "view"
  >;

  getBountyCount: TypedContractMethod<[], [bigint], "view">;

  getSubmission: TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [BountyEscrow.SubmissionStructOutput],
    "view"
  >;

  getSubmissionCount: TypedContractMethod<
    [bountyId: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  selectWinner: TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submissions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint] & {
        submitter: string;
        contentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  submitWork: TypedContractMethod<
    [bountyId: BigNumberish, contentHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REFUND_GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bounties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string, bigint, bigint] & {
        creator: string;
        amount: bigint;
        deadline: bigint;
        status: bigint;
        winner: string;
        metadataHash: string;
        createdAt: bigint;
        submissionCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "bountySubmissionCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelBounty"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[bountyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createBounty"
  ): TypedContractMethod<
    [amount: BigNumberish, deadline: BigNumberish, metadataHash: BytesLike],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getBounty"
  ): TypedContractMethod<
    [bountyId: BigNumberish],
    [BountyEscrow.BountyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBountyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubmission"
  ): TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [BountyEscrow.SubmissionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubmissionCount"
  ): TypedContractMethod<[bountyId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectWinner"
  ): TypedContractMethod<
    [bountyId: BigNumberish, submissionId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submissions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint] & {
        submitter: string;
        contentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [bountyId: BigNumberish, contentHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BountyCancelled"
  ): TypedContractEvent<
    BountyCancelledEvent.InputTuple,
    BountyCancelledEvent.OutputTuple,
    BountyCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BountyCreated"
  ): TypedContractEvent<
    BountyCreatedEvent.InputTuple,
    BountyCreatedEvent.OutputTuple,
    BountyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionCreated"
  ): TypedContractEvent<
    SubmissionCreatedEvent.InputTuple,
    SubmissionCreatedEvent.OutputTuple,
    SubmissionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerSelected"
  ): TypedContractEvent<
    WinnerSelectedEvent.InputTuple,
    WinnerSelectedEvent.OutputTuple,
    WinnerSelectedEvent.OutputObject
  >;

  filters: {
    "BountyCancelled(uint256,address)": TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;
    BountyCancelled: TypedContractEvent<
      BountyCancelledEvent.InputTuple,
      BountyCancelledEvent.OutputTuple,
      BountyCancelledEvent.OutputObject
    >;

    "BountyCreated(uint256,address,uint256,uint256,bytes32)": TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;
    BountyCreated: TypedContractEvent<
      BountyCreatedEvent.InputTuple,
      BountyCreatedEvent.OutputTuple,
      BountyCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RefundClaimed(uint256,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "SubmissionCreated(uint256,uint256,address,bytes32)": TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;
    SubmissionCreated: TypedContractEvent<
      SubmissionCreatedEvent.InputTuple,
      SubmissionCreatedEvent.OutputTuple,
      SubmissionCreatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "WinnerSelected(uint256,uint256,address,uint256)": TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
    WinnerSelected: TypedContractEvent<
      WinnerSelectedEvent.InputTuple,
      WinnerSelectedEvent.OutputTuple,
      WinnerSelectedEvent.OutputObject
    >;
  };
}
